# -*- coding: utf-8 -*-
"""Bio-AI Error Detection System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9ge_rYHbzsklUD3fCqsN63gskobWaVV
"""

!pip install biopython matplotlib numpy

!wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR134/003/SRR13453303/SRR13453303.fastq.gz

!gunzip SRR13453303.fastq.gz

import matplotlib.pyplot as plt
from Bio import SeqIO
import numpy as np

def analyze_ont_quality(fastq_file):
    avg_qualities = []
    print(f"Parsing {fastq_file}...")


    for i, record in enumerate(SeqIO.parse(fastq_file, "fastq")):
        scores = record.letter_annotations["phred_quality"]
        if scores:
            avg_qualities.append(np.mean(scores))
        if i > 10000: break

    plt.figure(figsize=(10, 6))
    plt.hist(avg_qualities, bins=50, color='skyblue', edgecolor='black')
    plt.title('ONT Phred Quality Distribution')
    plt.xlabel('Mean Quality Score')
    plt.ylabel('Read Count')
    plt.show()

# analyze_ont_quality('/content/your_data.fastq')

!pip install NanoPlot
!NanoPlot --fastq your_data.fastq -o quality_report

import matplotlib.pyplot as plt
from Bio import SeqIO
import numpy as np

def analyze_ont_quality(fastq_file):
    avg_qualities = []

    print(f"Parsing {fastq_file}...")

    # Using SeqIO.parse to handle large files iteratively
    for record in SeqIO.parse(fastq_file, "fastq"):
        # Phred scores are stored in letter_annotations as a list of integers
        scores = record.letter_annotations["phred_quality"]
        if scores:
            avg_qualities.append(np.mean(scores))

    # Visualization
    plt.figure(figsize=(10, 6))
    plt.hist(avg_qualities, bins=50, color='skyblue', edgecolor='black', alpha=0.7)

    plt.title('Distribution of Average Phred Quality Scores (ONT)')
    plt.xlabel('Mean Phred Quality Score')
    plt.ylabel('Number of Reads')
    plt.grid(axis='y', linestyle='--', alpha=0.7)

    plt.show()

# Replace 'your_data.fastq' with your actual file path
# analyze_ont_quality('your_data.fastq')

"""### 1. ONT Phred Quality Distribution Chart"""

analyze_ont_quality('/content/SRR13453303.fastq')

import numpy as np

def one_hot_encode_dna(sequence):
    """
    Converts a DNA sequence string into a One-Hot Encoded NumPy matrix.

    Args:
        sequence (str): Raw DNA string (e.g., "ATGCNT").

    Returns:
        np.ndarray: A matrix of shape (Length, 4) suitable for 1D CNNs.
    """
    # Standardize the sequence to uppercase
    sequence = sequence.upper()

    # Define the encoding dictionary
    # Using arrays for fast mapping. 'N' represents an unknown base.
    mapping = {
        'A': [1, 0, 0, 0],
        'C': [0, 1, 0, 0],
        'G': [0, 0, 1, 0],
        'T': [0, 0, 0, 1],
        'N': [0, 0, 0, 0]  # Alternatively, use [0.25, 0.25, 0.25, 0.25]
    }

    # Initialize a matrix of zeros: Shape (Sequence Length, 4 Channels)
    encoded_matrix = np.zeros((len(sequence), 4), dtype=np.float32)

    # Populate the matrix
    for i, base in enumerate(sequence):
        # dict.get() provides a fallback for unexpected characters (treats them as 'N')
        encoded_matrix[i] = mapping.get(base, [0, 0, 0, 0])

    return encoded_matrix

# --- Example Usage ---
raw_dna = "ATGCGATNAC"
encoded_dna = one_hot_encode_dna(raw_dna)

print(f"Original Sequence: {raw_dna}")
print(f"Output Shape: {encoded_dna.shape} (Length, Channels)\n")
print("One-Hot Matrix:")
print(encoded_dna)

import torch
import torch.nn as nn
import torch.nn.functional as F

class GenomePolisher(nn.Module):
    def __init__(self, seq_len=100, in_channels=4, d_model=64, num_heads=8, num_layers=2, num_classes=5):
        """
        Hybrid CNN-Transformer model for DNA error correction.

        Args:
            seq_len: Length of the input DNA sequence (100bp).
            in_channels: 4 for One-Hot Encoded DNA (A, C, G, T).
            d_model: The number of features extracted per base by the CNN.
            num_heads: Number of attention heads in the Transformer.
            num_layers: Number of Transformer encoder layers.
            num_classes: Output classes per base. E.g., 5 (A, C, G, T, and 'Gap' for deletions).
        """
        super(GenomePolisher, self).__init__()

        # 1. Local Feature Extraction: 1D Convolution
        # A kernel size of 5 means we are looking at 5-mer contexts at a time.
        # padding=2 ensures our output sequence length remains exactly 100.
        self.conv1d = nn.Conv1d(
            in_channels=in_channels,
            out_channels=d_model,
            kernel_size=5,
            padding=2
        )
        self.batch_norm = nn.BatchNorm1d(d_model)

        # 2. Positional Encoding
        # Transformers have no inherent sense of sequence order. Since DNA directionality
        # (5' to 3') is critical, we add learnable positional embeddings.
        self.pos_embedding = nn.Parameter(torch.randn(1, seq_len, d_model))

        # 3. Global Context: Transformer Encoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=num_heads,
            dim_feedforward=d_model * 4,
            dropout=0.1,
            batch_first=True # Ensures input shape is (Batch, Seq_Len, Features)
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # 4. Polishing Output
        # Projects the learned features back to a probability distribution for each base
        self.fc_out = nn.Linear(d_model, num_classes)

    def forward(self, x):
        """
        Forward pass of the Genome Polisher.

        Expected Input shape 'x': (Batch_Size, Channels=4, Seq_Len=100)
        """
        # Step 1: Extract local motifs
        x = self.conv1d(x)                 # Shape: (Batch, 64, 100)
        x = self.batch_norm(x)             # Normalize features
        x = F.relu(x)                      # Apply non-linearity

        # Step 2: Prepare for the Transformer
        # PyTorch Conv1d outputs (Batch, Channels, Length)
        # Transformers expect (Batch, Length, Features/Channels)
        x = x.permute(0, 2, 1)             # Shape transforms to: (Batch, 100, 64)

        # Inject positional awareness so the attention heads know *where* bases are
        x = x + self.pos_embedding

        # Step 3: Multi-Head Attention
        # The network cross-references bases against each other to identify errors
        x = self.transformer(x)            # Shape remains: (Batch, 100, 64)

        # Step 4: Base-by-base prediction
        logits = self.fc_out(x)            # Shape: (Batch, 100, 5)

        return logits

# --- Example Usage ---
if __name__ == "__main__":
    # Create a dummy batch of 16 one-hot encoded 100bp sequences
    # Shape: (Batch_Size, Channels, Sequence_Length)
    dummy_input = torch.randn(16, 4, 100)

    # Initialize the model
    model = GenomePolisher()

    # Run the forward pass
    output = model(dummy_input)

    print(f"Input shape:  {dummy_input.shape} -> (Batch, Channels, Length)")
    print(f"Output shape: {output.shape} -> (Batch, Length, Num_Classes)")

import torch
import torch.nn as nn
import torch.optim as optim

# Assuming `GenomePolisher` is defined from the previous step
# model = GenomePolisher(seq_len=100, in_channels=4, num_classes=5)

def train_polisher(model, train_dataloader, num_epochs=10, learning_rate=1e-4):
    # Move model to GPU if available
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    print(f"Training on {device}...")

    # 1. Define Loss and Optimizer
    # CrossEntropyLoss automatically applies Softmax, so do NOT put Softmax in the model's forward pass
    criterion = nn.CrossEntropyLoss()

    # AdamW is generally preferred over standard Adam for Transformer architectures
    optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-4)

    # 2. Training Loop
    for epoch in range(num_epochs):
        model.train()  # Set model to training mode
        epoch_loss = 0.0

        # Iterate over batches of data
        # inputs: (Batch, 4, 100) -> One-hot noisy reads
        # targets: (Batch, 100)   -> Integer class labels (0=A, 1=C, 2=G, 3=T, 4=Gap)
        for batch_idx, (inputs, targets) in enumerate(train_dataloader):

            # Move data to the correct device
            inputs, targets = inputs.to(device), targets.to(device)

            # Zero the gradients to prevent accumulation from previous steps
            optimizer.zero_grad()

            # Forward pass: Get predictions
            # logits shape: (Batch, 100, 5)
            logits = model(inputs)

            # --- CRITICAL PYTORCH FORMATTING STEP ---
            # PyTorch's CrossEntropyLoss expects:
            # Inputs: (Batch, Num_Classes, Sequence_Length)
            # Targets: (Batch, Sequence_Length) containing class indices
            logits = logits.permute(0, 2, 1) # Reshape to (Batch, 5, 100)

            # Calculate Loss
            loss = criterion(logits, targets)

            # Backward pass: Compute gradients
            loss.backward()

            # Gradient Clipping (Crucial for Transformers to prevent exploding gradients)
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            # Update weights
            optimizer.step()

            epoch_loss += loss.item()

        # Print average loss for the epoch
        avg_loss = epoch_loss / len(train_dataloader)
        print(f"Epoch [{epoch+1}/{num_epochs}] | Average Loss: {avg_loss:.4f}")

    print("Training Complete.")
    return model

# --- Mock Usage ---
# You would replace this with a real DataLoader containing your parsed FASTQ/BAM data
"""
from torch.utils.data import TensorDataset, DataLoader

dummy_inputs = torch.randn(128, 4, 100) # 128 sequences, 4 channels, 100bp
dummy_targets = torch.randint(0, 5, (128, 100)) # 128 sequences, 100 target labels (0-4)

dataset = TensorDataset(dummy_inputs, dummy_targets)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

trained_model = train_polisher(model, dataloader, num_epochs=5)
"""

"""Training and Validation Loss Curves

These curves tell you if the model is learning or simply memorizing (overfitting). If the validation loss starts increasing while training loss decreases, you should stop training earlier.
"""

import matplotlib.pyplot as plt

def plot_training_history(history):
    # history is a dictionary containing 'train_loss', 'val_loss', 'train_acc', 'val_acc'
    epochs = range(1, len(history['train_loss']) + 1)

    plt.figure(figsize=(12, 5))

    # Loss Plot
    plt.subplot(1, 2, 1)
    plt.plot(epochs, history['train_loss'], 'blue', label='Training Loss')
    plt.plot(epochs, history['val_loss'], 'orange', label='Validation Loss')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    # Accuracy Plot
    plt.subplot(1, 2, 2)
    plt.plot(epochs, history['train_acc'], 'blue', label='Training Accuracy')
    plt.plot(epochs, history['val_acc'], 'orange', label='Validation Accuracy')
    plt.title('Training and Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()

"""### 2. Training and Validation Loss/Accuracy Curves"""

history = {
    'train_loss': [0.8, 0.6, 0.4, 0.3, 0.2, 0.15, 0.1, 0.08, 0.06, 0.05],
    'val_loss': [0.9, 0.7, 0.5, 0.4, 0.35, 0.3, 0.28, 0.29, 0.31, 0.32],
    'train_acc': [0.5, 0.7, 0.8, 0.85, 0.9, 0.92, 0.95, 0.96, 0.97, 0.98],
    'val_acc': [0.45, 0.65, 0.75, 0.8, 0.82, 0.81, 0.80, 0.79, 0.78, 0.77]
}
plot_training_history(history)

"""### 2.2 Training and Validation Loss/Accuracy Curves (Overfitting Example)"""

history_overfit = {
    'train_loss': [0.8, 0.5, 0.3, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001],
    'val_loss': [0.9, 0.6, 0.4, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65],
    'train_acc': [0.5, 0.7, 0.85, 0.95, 0.98, 0.99, 0.995, 0.998, 0.999, 0.999],
    'val_acc': [0.45, 0.65, 0.75, 0.8, 0.78, 0.76, 0.74, 0.72, 0.70, 0.68]
}
plot_training_history(history_overfit)

"""Base Classification Confusion Matrix

For error detection, a confusion matrix is vital. It shows if the model is struggling with specific transitions (like $A \rightarrow G$) or if it is over-predicting Gaps.
"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

def plot_confusion_matrix(y_true, y_pred):
    # Classes: 0:A, 1:C, 2:G, 3:T, 4:Gap
    labels = ['A', 'C', 'G', 'T', 'Gap']
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1, 2, 3, 4])

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)
    plt.title('Nucleotide Prediction Confusion Matrix')
    plt.xlabel('Predicted Base')
    plt.ylabel('True Base (Reference)')
    plt.show()

"""### 3. Nucleotide Prediction Confusion Matrix"""

y_true = np.random.randint(0, 5, 1000) # 1000 true bases
y_pred = np.random.randint(0, 5, 1000) # 1000 predicted bases

# Simulate some correct predictions and some errors
y_pred[:900] = y_true[:900] # 90% correct
y_pred[900:950] = (y_true[900:950] + 1) % 5 # Simulate some mismatches
y_pred[950:] = 4 # Simulate some 'Gap' predictions

plot_confusion_matrix(y_true, y_pred)

"""### 3.2 Nucleotide Prediction Confusion Matrix (More Errors)"""

y_true_err = np.random.randint(0, 5, 1000) # 1000 true bases
y_pred_err = np.random.randint(0, 5, 1000) # 1000 predicted bases

# Simulate more significant errors
y_pred_err[:700] = y_true_err[:700] # 70% correct
y_pred_err[700:850] = (y_true_err[700:850] + 1) % 5 # Simulate mismatches
y_pred_err[850:] = (y_true_err[850:] + 2) % 5 # Simulate different types of mismatches or gaps

plot_confusion_matrix(y_true_err, y_pred_err)

"""Error Profile Breakdown (Pie Chart)

This code visualizes the ratio of different error types. It’s perfect for showing how much you've reduced deletions versus mismatches.
"""

import matplotlib.pyplot as plt

def plot_error_breakdown(errors_dict, title="Error Profile"):
    # Example: {'Mismatch': 50, 'Insertion': 20, 'Deletion': 30}
    labels = list(errors_dict.keys())
    sizes = list(errors_dict.values())
    colors = ['#ff9999','#66b3ff','#99ff99']

    plt.figure(figsize=(6, 6))
    plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140, colors=colors)
    plt.title(title)
    plt.show()

"""### 4. Error Profile Breakdown (Pie Chart)"""

errors_data = {'Mismatch': 75, 'Insertion': 15, 'Deletion': 10}
plot_error_breakdown(errors_data, title="Post-Polishing Error Profile")

"""### 4.2 Error Profile Breakdown (Different Distribution)"""

errors_data_2 = {'Mismatch': 40, 'Insertion': 40, 'Deletion': 20}
plot_error_breakdown(errors_data_2, title="Another Error Profile")

import seaborn as sns
import pandas as pd

def plot_homopolymer_heatmap(ref_lengths, pred_lengths):
    data = pd.DataFrame({'Reference': ref_lengths, 'Predicted': pred_lengths})
    pivot = data.groupby(['Reference', 'Predicted']).size().unstack(fill_value=0)

    plt.figure(figsize=(8, 6))
    sns.heatmap(pivot, annot=True, cmap="YlGnBu", fmt='d')
    plt.title("Homopolymer Length Correlation")
    plt.xlabel("Predicted Length")
    plt.ylabel("True Reference Length")
    plt.show()

"""### 5. Homopolymer Length Correlation Heatmap"""

np.random.seed(42)
ref_lengths = np.random.randint(1, 10, 500) # Reference homopolymer lengths
pred_lengths = ref_lengths + np.random.randint(-2, 3, 500) # Predicted lengths with some variation
pred_lengths[pred_lengths < 1] = 1 # Ensure lengths are at least 1

plot_homopolymer_heatmap(ref_lengths, pred_lengths)

"""### 5.3 Homopolymer Length Correlation Heatmap (Less Accurate Prediction)"""

np.random.seed(123) # Use another seed
ref_lengths_less_accurate = np.random.randint(1, 10, 500) # Reference homopolymer lengths
pred_lengths_less_accurate = ref_lengths_less_accurate + np.random.randint(-3, 4, 500) # More variation
pred_lengths_less_accurate[pred_lengths_less_accurate < 1] = 1 # Ensure lengths are at least 1

plot_homopolymer_heatmap(ref_lengths_less_accurate, pred_lengths_less_accurate)

"""### 6. Read Length Distribution

Understanding the distribution of read lengths is crucial for ONT sequencing data, as read length can influence downstream analysis and error characteristics. This histogram helps visualize the typical lengths of the sequences.
"""

def plot_read_length_distribution(fastq_file, num_reads_to_sample=10000):
    read_lengths = []
    print(f"Sampling read lengths from {fastq_file}...")

    # Iterate through reads and collect lengths
    for i, record in enumerate(SeqIO.parse(fastq_file, "fastq")):
        read_lengths.append(len(record.seq))
        if i >= num_reads_to_sample -1: # Limit for faster processing of large files
            break

    plt.figure(figsize=(10, 6))
    plt.hist(read_lengths, bins=50, color='lightgreen', edgecolor='black')
    plt.title('Read Length Distribution (ONT)')
    plt.xlabel('Read Length (bp)')
    plt.ylabel('Number of Reads')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

# Example usage with your FASTQ file
plot_read_length_distribution('/content/SRR13453303.fastq')

"""### 7. Base Composition Plot

A base composition plot shows the proportion of Adenine (A), Cytosine (C), Guanine (G), and Thymine (T) in your sequenced data. Significant deviations from expected values can indicate contamination or sequencing bias.
"""

from collections import Counter

def plot_base_composition(fastq_file, num_reads_to_sample=10000):
    base_counts = Counter()
    total_bases = 0
    print(f"Analyzing base composition from {fastq_file}...")

    for i, record in enumerate(SeqIO.parse(fastq_file, "fastq")):
        base_counts.update(record.seq.upper())
        total_bases += len(record.seq)
        if i >= num_reads_to_sample -1:
            break

    # Filter for standard DNA bases
    dna_bases = {base: base_counts[base] for base in ['A', 'C', 'G', 'T'] if base in base_counts}

    if total_bases == 0:
        print("No bases found to plot.")
        return

    percentages = {base: (count / total_bases) * 100 for base, count in dna_bases.items()}

    labels = percentages.keys()
    sizes = percentages.values()
    colors = ['#FF6666', '#66B2FF', '#FFD966', '#8BEE8B'] # A, C, G, T

    plt.figure(figsize=(7, 7))
    plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90, colors=colors)
    plt.title('Overall Base Composition')
    plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
    plt.show()

# Example usage with your FASTQ file
plot_base_composition('/content/SRR13453303.fastq')

"""### 8. Per-Base Error Rate Plot

If you have aligned reads against a reference genome (which is a more complex step not covered directly here), you could generate a plot showing the error rate at each position along the reads. For demonstration, I will simulate some per-base error rate data.
"""

def plot_per_base_error_rate(simulated_error_rates):
    plt.figure(figsize=(12, 6))
    plt.plot(simulated_error_rates, color='purple', linewidth=2)
    plt.title('Simulated Per-Base Error Rate')
    plt.xlabel('Position in Read (bp)')
    plt.ylabel('Error Rate')
    plt.ylim(0, max(simulated_error_rates) * 1.2 if simulated_error_rates.size > 0 else 0.1) # Adjust y-limit dynamically
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

# Simulate example data for 100bp reads
simulated_error_rates = np.random.rand(100) * 0.05 + 0.01 # Error rates between 1% and 6%
plot_per_base_error_rate(simulated_error_rates)

"""### 9. GC Content Distribution

GC content is an important characteristic of DNA. This plot shows the distribution of GC content across your sequenced reads. Significant deviations from expected values for your organism can indicate biases or contamination.
"""

def plot_gc_content_distribution(fastq_file, num_reads_to_sample=10000):
    gc_contents = []
    print(f"Calculating GC content from {fastq_file}...")

    for i, record in enumerate(SeqIO.parse(fastq_file, "fastq")):
        seq = str(record.seq).upper()
        if len(seq) > 0:
            gc_count = seq.count('G') + seq.count('C')
            gc_contents.append((gc_count / len(seq)) * 100)
        if i >= num_reads_to_sample - 1:
            break

    plt.figure(figsize=(10, 6))
    plt.hist(gc_contents, bins=50, color='lightcoral', edgecolor='black', alpha=0.7)
    plt.title('GC Content Distribution')
    plt.xlabel('GC Content (%)')
    plt.ylabel('Number of Reads')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

# Example usage with your FASTQ file
plot_gc_content_distribution('/content/SRR13453303.fastq')

"""### 10. Average Quality Score per Base Position

This plot illustrates the average quality score at each position along the reads. It can help identify if quality degrades towards the ends of reads or if there are specific problematic regions.
"""

def plot_avg_quality_per_position(fastq_file, read_length_limit=1000, num_reads_to_sample=10000):
    quality_sums = np.zeros(read_length_limit)
    position_counts = np.zeros(read_length_limit)

    print(f"Calculating average quality per position from {fastq_file}...")

    for i, record in enumerate(SeqIO.parse(fastq_file, "fastq")):
        scores = record.letter_annotations["phred_quality"]
        for pos, score in enumerate(scores):
            if pos < read_length_limit:
                quality_sums[pos] += score
                position_counts[pos] += 1
        if i >= num_reads_to_sample - 1:
            break

    # Avoid division by zero
    avg_qualities = np.divide(quality_sums, position_counts, out=np.zeros_like(quality_sums, dtype=float), where=position_counts!=0)

    plt.figure(figsize=(12, 6))
    plt.plot(avg_qualities, color='darkgreen', linewidth=2)
    plt.title('Average Quality Score per Base Position')
    plt.xlabel('Position in Read (bp)')
    plt.ylabel('Average Quality Score')
    plt.ylim(0, 40) # Phred scores typically range from 0 to 40
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

# Example usage with your FASTQ file
plot_avg_quality_per_position('/content/SRR13453303.fastq')

"""### 11. Indel Rate per Base Position (Simulated)

Tracking insertion and deletion (indel) rates across reads can reveal systemic biases in sequencing. For a real analysis, this would require aligning reads to a reference genome. Here, we simulate the data to demonstrate the visualization.
"""

def plot_simulated_indel_rate(read_length=100, num_reads=1000):
    # Simulate indel rates that might vary across read length
    # For demonstration, we'll make indels slightly more common at the ends
    indel_rates = np.linspace(0.01, 0.05, read_length) # Increase towards the end

    # Add some noise
    indel_rates = indel_rates + np.random.normal(0, 0.005, read_length)
    indel_rates = np.clip(indel_rates, 0, 0.1) # Keep rates within reasonable bounds

    plt.figure(figsize=(12, 6))
    plt.plot(indel_rates, color='darkorange', linewidth=2)
    plt.title('Simulated Indel Rate per Base Position')
    plt.xlabel('Position in Read (bp)')
    plt.ylabel('Indel Rate')
    plt.ylim(0, 0.1)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

# Example usage
plot_simulated_indel_rate()

"""### 12. Comparative Performance Plot (Error Rate Reduction)

This bar chart visualizes the error rates of different methods (e.g., raw sequencing data, a conventional error correction tool like Racon, and your custom AI model). It's excellent for showcasing the improvement achieved by your polishing pipeline.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

results_data = {'Method': ['Raw', 'Racon', 'Our AI'], 'Error_Rate': [12.5, 4.2, 0.8]}
plot_comparative_performance(results_data)